### ISSUE TITLE
Add Outputs and Basic Commands for Wrist/Elevator

### ISSUE THREAD

**Issue by legoguy1000** [Frc5572/FRC2024#13]

**Comment by Merridew1** [comment]
**Commands** 
Elevator:
- Elevator Up
- Elevator Down
- Home position
- Auto climb?
- Amp position
- Trap position

Wrist:
- Home angle
- Variable speaker angle
- Turn to angle
- Trap angle
- Amp angle

**Comment by legoguy1000** [comment]
completed by #17
