### ISSUE TITLE
Add Command to Shoot based on Distance

### ISSUE THREAD

**Issue by legoguy1000** [Frc5572/FRC2024#15]
Needs to take distance from target to set below

- Shooter Speed
- Wrist Angle
- Elevator Height

**Comment by gvaldez7206** [comment]
Shooter:

- Command that takes distance from swerve to the scoring place, then set a speed for it 
- From there, we can use this command to score in different positions

**Comment by legoguy1000** [comment]
Add the command to here https://github.com/Frc5572/FRC2024/blob/main/src/main/java/frc/robot/commands/CommandFactory.java
