### ISSUE TITLE
Add Elevator & Wrist Subsystem

### ISSUE THREAD

**Issue by legoguy1000** [Frc5572/FRC2024#2]
Elevator

- 1 Falcon

Wrist

- 1 Neo

**Comment by owenflatman** [comment]
1/24 
@Merridew1 and I finished IO java file, added talon and spark max, have to finish sim ElevatorWrist file.

**Comment by owenflatman** [comment]
Today we finished real, made progress on elevator profile PID, and will continue working on Saturday.
- Reed
