### ISSUE TITLE
Possible button mapping

### ISSUE THREAD

**Issue by owenflatman** [Frc5572/FRC2024#35]
Work in progress
https://docs.google.com/presentation/d/1oJZhHlrYburMSjcasFFbvPNTfOH3J4_1lejOg0Bpqvw/edit#slide=id.g2670428c9e5_1_0

**Comment by Merridew1** [comment]
operator needs to control the elevator up and down, the winch(climb), the intake, the wrist angle, and the shooting

**Comment by Merridew1** [comment]
mapping and slideshow finished, still needs to be implemented
