### ISSUE TITLE
Add Shooter Subsystem

### ISSUE THREAD

**Issue by legoguy1000** [Frc5572/FRC2024#4]
- 2 Vortex Motors

closed by #11

**Comment by gvaldez7206** [comment]
Added Shooter IO, Shooter TalonFx, and Shooter classes as well as adding the following methods: 

- setTopMotor
- setBottomMotor
- UpdateInputs
We also created a shooter class added initialized variables for the id of both the top and bottom motor on the Constants class. 
We need to work on adding more functions, or other stuff to the classes.
