### ISSUE TITLE
Tune PID for Wrist

### ISSUE THREAD

**Issue by legoguy1000** [Frc5572/FRC2024#67]
We tested with .2 (20%) power (2.4V), we can probably go higher but assuming the max range of motion is like 90 degrees (probably more but less than 180) the P to get max power would be `P = 2.4/90`. As such at max error 90 degrees, u get 2.4 Volts. We need to know what the actual max range of motion is and then figure out how fast we want to move but this is a good way to start.

**Comment by wilsonwatson** [comment]
Closed by #75.
