### ISSUE TITLE
Add Climber Subsystem

### ISSUE THREAD

**Issue by legoguy1000** [Frc5572/FRC2024#8]
- 2 Neo Motors

**Comment by legoguy1000** [comment]
Going to require some sort of sensor/method to determine location and when to stop

**Comment by legoguy1000** [comment]
Is this ready for review? I got mixed messages today?

**Comment by owenflatman** [comment]
Besides not having the height and angle needed for climbing, along with the max and min angles when climbing or not, it is ready

**Comment by legoguy1000** [comment]
> Besides not having the height and angle needed for climbing, along with the max and min angles when climbing or not, it is ready

Height and angle of what? The elevator and wrist? That shouldn't matter at this time. I think the only real question was the height of the climb. Let's get answers to our questions. I want this done before practice Wednesday.

**Comment by legoguy1000** [comment]
Can we have this finished by practice tomorrow? if its ready lets get the merge request open.

**Comment by legoguy1000** [comment]
We have 2 different branches that need to get merged @owenflatman @aidan-underwood !!!

- https://github.com/Frc5572/FRC2024/compare/main...climber
- https://github.com/Frc5572/FRC2024/compare/main...Climber-Subsystem

**Comment by owenflatman** [comment]
I didn't know the other branch even existed

**Comment by aidan-underwood** [comment]
Ignore climber-subsystem, not sure where this came from.
